# Generated by Django 5.2.4 on 2025-07-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.affiliatelink'),
        ),
    ]
